### ISSUE TITLE
[Bug] Hanging during download

### ISSUE THREAD

**Issue by MrBrown321** [RobotsOnDrugs/BDSM#14] opened 2022-12-30 19:09 UTC
### Problem behavior

the downloader keeps crashing like this nothing moves after some minutes of downloading
![image](https://user-images.githubusercontent.com/121691401/210104525-6bb0cd57-962d-4716-ad8a-4c1f19a34fcc.png)

**Comment by RobotsOnDrugs** [comment] 2022-12-31 10:18
My best guess is that it's hanging on the write call to write a downloaded buffer to the file, possibly because you have no more space on the disk or there is some hardware issue that prevents writing to the file. I'm not actually sure what the behavior for that API call is when there is no more space on disk, but I *think* by default it just blocks until it can write something. I can add a timeout for it so that it will give up instead of just hanging, but that wouldn't solve the issue. I also will be setting up better logging so that things like this can be traced better. Unfortunately however, there is no way for me to really troubleshoot this without directly debugging the program on your machine. I have a pretty good idea of where the issue is in the code, but I don't know exactly what's causing it to hang like that.

Are there any errors that show up in the log? Also, are you able to download these mods with KKManager?

**Comment by MrBrown321** [comment] 2022-12-31 16:12
yes i can download it with kk with no problems at all also there is other problem that the BDSM marks like 50 gigs of mods to delete idk why...

i use .net7 btw

**Comment by RobotsOnDrugs** [comment] 2022-12-31 20:26
Again, are there any errors that show up in the log? If there's anything there, it could provide some clues. If you're not sure, you can just paste the log and I'll look through it.
Also, are you downloading to a network drive? Temporary connection problems can cause writes to stall. I can have BDSM try again if it's having issues like this.

Most likely, it's marking those mods for deletion because they're not fully downloaded (and therefore corrupt and unusable) and it didn't have a chance to clean up before.

The next release will have a mechanism for timing out write download operations that take too long so that it will error out instead of hanging forever (and retry a couple times before giving up), and better logging is coming after that.

**Comment by RobotsOnDrugs** [comment] 2023-01-04 17:08
Unfortunately, this is proving to be difficult to implement properly, so I'll have to push it back a bit. I still think it's important to gracefully handle problems during download though. I may do some better separation of "library" code and the logging work before then as well as some minor features.

**Comment by RobotsOnDrugs** [comment] 2023-01-07 22:14
Considering how much of a pain it was to fix this, I'm considering this blocked by #15, #16, and #18. Once there's at least enough logging and testability for DownloadFileChunks, I can work on this with a lot more insight into what makes it get weird when retrying and aborting the downloads. The logging should also give some more insight into what's actually going on when it hangs for you.

**Comment by RobotsOnDrugs** [comment] 2023-01-11 23:11
@MrBrown321 Can you test this with a debug build of 0.3.5 and provide the debug log? If you do encounter the same issue, use Ctrl-C to exit and do not close the console window or force kill the process. If you do, some log messages may not be written.

**Comment by RobotsOnDrugs** [comment] 2023-01-22 18:41
I can't reproduce this and there have been no other reports of this. It may have been fixed with 0.3.8 or earlier as well. If there are no more reports or information this week, I'll close this issue. Feel free to make another report if this happens again for you.

**Closed as completed** 2023-02-02 13:38 UTC
Labels: bug, invalid, unable to reproduce
