### ISSUE TITLE
[Bug] Mods folder is wiped out

### ISSUE THREAD

**Issue by ghost** [RobotsOnDrugs/BDSM#28] opened 2023-01-16 18:07 UTC
### Problem behavior

So I ran this program to download new mods, but all of a sudden it started deleting stuff and then it closed suddenly. When i checked the mods folder, my entire mods is wiped out except MyMods.
[BDSM.log](https://github.com/RobotsOnDrugs/BDSM/files/10428363/BDSM.log)

### Expected behavior

Download new mods

### Steps to reproduce

Run the executable

**Comment by RobotsOnDrugs** [comment] 2023-01-16 18:54
Paste your UserConfiguration.yaml. I suspect the issue is there. Also, I would not recommend running without a prompt unless you're absolutely sure everything is set up correctly.

**Comment by ghost** [comment] 2023-01-16 19:00
![Screenshot 2023-01-17 002722](https://user-images.githubusercontent.com/76907302/212749377-fcafe7a1-c3d9-4d38-be03-5122f7883122.png)
Couldn't upload the file so here's the ss. Also abt the prompt, when i tried running it again, it didn't asked for any prompt and was just stuck at "Scanning Servers". Also the download speed is really low (20-90 kbps avg). Not sure what's going on.

**Comment by RobotsOnDrugs** [comment] 2023-01-16 20:37
Your configuration looks fine. You are using the latest release (0.3.6), right? There might be a bug with an older version that messes up the scanning in specific cases. I've tested with dropped connections and never had an issue with the scan not having the correct count and still proceeding (which would mess up the sync and delete stuff it shouldn't), so I'm not sure what's going on here. It looks like an issue that was already fixed, but I suppose a regression that I couldn't reproduce is possible. There might be some more information in a debug log you can get from a debug build in the releases if you have a similar issue again. Try again with a debug build and with prompting turned on, and if the summary shows that there are only a few hundred files scanned with all those packs enabled, post both the normal log and the debug log and I'll investigate further.

> Couldn't upload the file so here's the ss. Also abt the prompt, when i tried running it again, it didn't asked for any prompt and was just stuck at "Scanning Servers". Also the download speed is really low (20-90 kbps avg). Not sure what's going on.

Sometimes the server is a bit overloaded and things will get slow, especially when a couple of the connections drop. I've noticed the same thing myself at times, and there's not much that can be done about it in the short term. Getting work spread across the other BR servers is a planned feature, but it will take time to do. Also, you've explicitly configured it to not prompt, so of course it won't. Change `PromptToContinue` to `true` and it will give you all the prompts, which is the default behavior.

Also, I do have #23 opened as a thing to implement so it would show summaries for each pack, which would make it easier to see issues similar to this one, but it'll have to wait until the server spreading work is done.

**Comment by RobotsOnDrugs** [comment] 2023-01-16 22:53
Something weird has been going on with the server in the last day (it's probably overloaded at the moment) and I had something similar happen during a scheduled task, but this was for a really old version that I forgot to replace. Every time I've run it with the latest version, I've gotten a proper list, even when a couple connections dropped. I can keep trying once my mods are done getting transferred back from a backup.

**Comment by RobotsOnDrugs** [comment] 2023-01-17 08:07
I can't reproduce this with the latest version. For anyone else coming across this, please comment if this issue has come up for you along with logs, including the debug log if possible. I'm leaving this open in the mean time and will investigate thoroughly if I encounter this myself during development.

**Comment by Aggelus** [comment] 2023-01-17 14:32
I also had most of the mods deleted, and the update after a few downloads, I'm testing the new version to see if the problem persists.
I advise not to use spaces in the name of the game folder, this seems to be a problem factor.

[BDSM.0.log](https://github.com/RobotsOnDrugs/BDSM/files/10435999/BDSM.0.log)

**Comment by RobotsOnDrugs** [comment] 2023-01-17 14:32
As well as my inability to reproduce the problem on the current version, I'm going to consider this blocked by #25, which is now the priority. Hopefully getting the underlying FTP messages will shed some light on this.

**Comment by RobotsOnDrugs** [comment] 2023-01-17 15:16
> I also had most of the mods deleted, and the update after a few downloads, I'm testing the new version to see if the problem persists. I advise not to use spaces in the name of the game folder, this seems to be a problem factor.
> 
> [BDSM.0.log](https://github.com/RobotsOnDrugs/BDSM/files/10435999/BDSM.0.log)

I didn't see your message just before I commented. Can you elaborate on how the spaces in the game path are a potential issue?
Also, I highly recommend using the latest version since there are essential improvements to it and this does not seem to be a regression. Using a debug version and providing a debug log from when the issues occurs again (if it does) could be helpful as well.

**Comment by Aggelus** [comment] 2023-01-17 17:59
The space in the game folder name causes some problems in the game, some error messages in the log, but it focuses more on the game not BDSM.
I'm using the latest version and it stopped downloading after only downloading 3 mods.
[BDSM.1.log](https://github.com/RobotsOnDrugs/BDSM/files/10438051/BDSM.1.log)
[BDSM.log](https://github.com/RobotsOnDrugs/BDSM/files/10438052/BDSM.log)

**Comment by ghost** [comment] 2023-01-17 19:30
After 15hrs of downloading 120gb mods, it got deleted again. Sorry man, but I've lost my complete trust on this software. I feel stupid wasting so much time on this. Here's the log in case you need it.
[BDSM.log](https://github.com/RobotsOnDrugs/BDSM/files/10438672/BDSM.log)
[BDSM.debug.log](https://github.com/RobotsOnDrugs/BDSM/files/10438673/BDSM.debug.log)

**Comment by SilverSly123** [comment] 2023-01-17 19:37
3059 files deleted.
Thanks a lot for the whole time you spend on that.
Maybe put some security on it like a question asking for the deletion.
Or just delete this project and play Little Poney instead.
Tchuss

**Comment by RobotsOnDrugs** [comment] 2023-01-18 05:34
I'm sorry it happened again, but I've always said to keep things backed up for a multitude of reasons even beyond this tool, and the prompt is on by default for a reason. It's a newer project and not as battle-tested so to speak as KKManager, so there are bound to be rough edges in rough circumstances, and I'm not offended if you want to stop using it given the current state of things. I appreciate the logs and I'll continue to investigate what exactly is triggering this and how to fix it.

**Comment by Aggelus** [comment] 2023-01-18 14:00
I left it downloading mods overnight and it only downloaded 2 gigs before it stopped saying it was done.
A solution to the problem of deleting mods would be to copy them to a backup folder instead of deleting them.
So the user himself can decide whether to delete them or not.

**Comment by RobotsOnDrugs** [comment] 2023-01-19 01:59
The issue is that it's not picking up all the files, so it's not going to download what it doesn't know about. It's the same reason it thinks it should delete more stuff than it should.

I feel like a broken record at this point, but I keep saying that people should keep backups. I appreciate the thought, but the problem with your suggestion is that it would end up copying **a lot** in this case and there's no way to know what a good backup place would be. The user has a lot more control keeping their own backup and a lot of people would not be happy either suddenly having their drive out of space or expecting a backup from BDSM and not getting one because it detects there is no space. Plus, it's kind of a messed up version of a proper backup. If we were talking about 5GB of stuff, it would be reasonable, but the mod repo is more than 200GB in total. Even cutting down to the base packs, it's still a lot.

If I can't track down the bug soon, what I'll do is put in a warning that ignores the prompt option if the number of files to delete is really high and force the user to fully type out 'continue anyway' or such.


On a side note, I fucking hate FTP and the scan process is basically a kludge to make up for the lack of server-side metadata. I'll be happy rewriting 90% of the code when this system gets replaced.

**Comment by RobotsOnDrugs** [comment] 2023-01-19 02:34
Also, implementing #23 (and #22, which will probably end up as a similar summary) should be helpful both for development and for users, so I'll be putting those in as part of the process.

**Comment by RobotsOnDrugs** [comment] 2023-01-19 16:20
I've added handling of server fuckery (and this fuckery really is server-side) to safeguard against bad scan results. I've also added a safeguard against marking a large number of files because of an obviously messed up scan result. This *should* resolve the issue, but I'd like as many people as possible to confirm with the upcoming release. I'm keeping this issue open until others can confirm that this is fixed for them just in case.

**Comment by hainiya** [comment] 2023-01-20 04:00
Why not make deletion optional, let us decide for ourselves whether to delete the mod or not

**Comment by RobotsOnDrugs** [comment] 2023-01-20 09:17
For the same reason KKManager doesn't make it optional. You don't need old mods. At best, you waste space and at worst, you get weird conflicts that break things. It's not even that common for mods to get deleted outside bleeding edge, and there's a good reason when one does get deleted from the repo. If you really want to hold onto a mod, copy it into mymods and don't complain if something breaks. There's nothing to be gained from hoarding obsolete mods.

**Comment by RobotsOnDrugs** [comment] 2023-01-24 03:51
Since I've heard people saying this fixes the problem for them, I've seen this only fix the problem, and there have been no further reports since the release, I'm considering this solved.

**Closed as completed by RobotsOnDrugs** 2023-01-24 03:51 UTC
Labels: bug
